### ISSUE TITLE
INSERT/UPDATE ... IF NOT EXISTS support

### ISSUE THREAD

**Issue by sergiofagostinho** [lawrencekgrant/vscode-cql#1]
Hi,

First of, thanks for making a CQL plugin for VSCode (there aren't many IDEs that support to it)!

I have been using the plugin, but I've noticed that the INSERT ... IF NOT EXISTS syntax highlight doesn't work. I'm using Cassandra 2.1, but this is supported since 2.0: http://www.datastax.com/dev/blog/lightweight-transactions-in-cassandra-2-0

Thanks,

**Comment by lawrencekgrant** [comment]
Thanks @sergiofagostinho for using the extension and thanks again for reporting this issue. IF NOT EXISTS should certainly be in here. I will get that added in the next release.

**Comment by lawrencekgrant** [comment]
It didn't come in the next release, but it came in the one that I just pushed out [0.4.8](https://marketplace.visualstudio.com/items?itemName=LawrenceGrant.cql). Ahead of it was two other things that needed to be done. Restructuring of the code so that I could make changes more easily was one. The other is execute functionality. So now you can execute statements against your cluster right from the extension. Thanks again for reporting the issue!
